version: "3.7"

services:
  db:
    build: ./db
    image: cs5224-hdbguru/postgis
    command: >
      -c ssl=on
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${HDBGURU_DB_USERNAME:?DB Usename must be specified}
      POSTGRES_PASSWORD: ${HDBGURU_DB_PASSWORD:?DB Password must be specified}
      POSTGRES_DB: ${HDBGURU_DB_NAME:?DB Name must be specified}
    volumes:
      - "./db/data/_processed:/tmp/data/_processed"
  searchserver:
    build: ./searchserver
    image: cs5224-hdbguru/searchserver
    # command: gunicorn --bind 0.0.0.0:31001 --worker-class=gevent --workers=5 server:app
    command: python3 server.py --port=31001 --dbaddr=db:5432
    depends_on:
      - db
    expose:
      - "31001"
    ports:
      - "31001:31001"
  dataserver:
    build: ./dataserver
    image: cs5224-hdbguru/dataserver
    command: python3 updatedb.py --dbaddr=db:5432
    depends_on:
      - db